path_classifiers:
  test:
    - test
  library:
    - libs
  docs:
    - docs

extraction:
  cpp:
    # install custom CMake version 3.20 (based on https://github.com/kahypar/mt-kahypar/pull/94/commits/fee8586ca083f43d3e87c36e324f321c78398f29)
    after_prepare:
      - "mkdir custom_cmake"
      - "wget --quiet -O - https://cmake.org/files/v3.20/cmake-3.20.6-linux-x86_64.tar.gz | tar --strip-components=1 -xz -C custom_cmake"
      - "export PATH=$(pwd)/custom_cmake/bin:${PATH}"
    configure:
      command:
        - cmake -S . -B build -DFICTION_CLI=ON -DFICTION_TEST=ON -DFICTION_PROGRESS_BARS=OFF -DMOCKTURTLE_EXAMPLES=OFF -DWARNINGS_AS_ERRORS=OFF
    index:
      build_command:
        - cmake --build build -j2
