version: 2

build:
  os: ubuntu-22.04

submodules:
  exclude: all
  recursive: false

sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
