version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    apt_packages:
      - cmake

sphinx:
  configuration: docs/conf.py

formats: [ ]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
