language: cpp

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

before_install:
  # fix linkage error with clang
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

before_script:
  # activate all python versions
  - pyenv global $(pyenv whence 2to3)
  # hand-pick python3
  - PY_CMD=python3

script:
# create build folder
- mkdir build
- cd build
# restore cache if it exists
- ([ ! -f $HOME/.cache/z3 ] || mv $HOME/.cache/z3 ./)
# set compiler, python executable, and Z3 build verbosity
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DPYTHON_EXECUTABLE=$(which $PY_CMD) -DBUILD_Z3_VERBOSE=TRUE ..
# build Z3 (takes some time) and cache it
- make -j2 z3
- mkdir -p $HOME/.cache
- mv z3/ $HOME/.cache/
# build fiction
- make -j2 fiction
# run integration tests
- ./fiction -ef ../test/integration.fc -l log.json

matrix:
 include:
  # ubuntu 18.04 gcc/g++7
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - libboost-all-dev
    
  # ubuntu 18.04 clang/clang++7
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - libboost-all-dev
