language: cpp

before_script:
  # install boost libraries
  - sudo apt install -qq libboost-all-dev
  # activate all python versions
  - pyenv global $(pyenv whence 2to3)
  # hand-pick python3
  - PY_CMD=python3

script:
- mkdir build
- cd build
# set compiler and python executable
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DPYTHON_EXECUTABLE=$(which $PY_CMD) ..
# build z3 (takes some time)
- travis_wait make -j2 z3
# build fiction
- make -j2 fiction

matrix:
 include:
  # ubuntu 16.04 gcc/g++7
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env: COMPILER=g++-7
    
  # ubuntu 16.04 clang/clang++7
  - os: linux
    dist: xenial
    sudo: required
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-7
        packages:
          - clang-7
    env: COMPILER=clang++-7
