language: cpp

before_script:
  # install boost libraries
  - sudo apt install -qq libboost-all-dev

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
- make fiction

matrix:
 include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env: COMPILER=g++-7
