language: cpp

cache: ccache

before_install:
  # fix linkage error with clang
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

before_script:
  # activate all python versions
  - pyenv global $(pyenv whence 2to3)
  # hand-pick python3
  - PY_CMD=python3

script:
# create build folder
- mkdir build
- cd build
# set compiler, python executable, and Z3 build verbosity
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DPYTHON_EXECUTABLE=$(which $PY_CMD) -DBUILD_Z3_VERBOSE=TRUE ..
# build fiction
- make -j2
# run integration tests
- ./fiction -ef ../test/integration.fc -l log.json

matrix:
 include:
  # ubuntu 18.04 gcc/g++7
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        packages:
          - libboost-all-dev
    
  # ubuntu 18.04 clang/clang++7
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    addons:
      apt:
        packages:
          - libboost-all-dev
