name: Clang-Tidy Review

on:
  pull_request:
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - 'libs/**'
      - '.github/workflows/clang-tidy-review.yml'
      - '!bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  clangtidy:
    runs-on: ubuntu-latest
    name: Clang-Tidy

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
          cache: 'pip'

      - name: Install pip packages
        uses: BSFishy/pip-action@v1
        with:
          requirements: ${{github.workspace}}/libs/mugen/requirements.txt

      - name: Setup Z3 Solver
        id: z3
        uses: cda-tum/setup-z3@v1
        with:
          version: ${{env.Z3_VERSION}}
          platform: linux
          architecture: x64
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Review code with Clang-Tidy
        uses: ZedThree/clang-tidy-review@v0.18.0
        id: review
        with:
          cmake_command: >
            cmake . -B build
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DFICTION_CLI=ON
            -DFICTION_TEST=ON
            -DFICTION_BENCHMARK=OFF
            -DFICTION_EXPERIMENTS=ON
            -DFICTION_Z3=ON
            -DFICTION_ENABLE_MUGEN=ON
            -DFICTION_PYTHON_BINDINGS=ON
            -DMOCKTURTLE_EXAMPLES=OFF
          build_dir: build
          config_file: '.clang-tidy'
          exclude: 'libs/*,docs/*,benchmarks/*,bib/*,*/pyfiction/pybind11_mkdoc_docstrings.hpp,*/pyfiction/documentation.hpp'
          split_workflow: true

      - name: Make sure that the review file exists
        id: check-review-output
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: 'clang-tidy-review-output.json'
          ignore_case: true

      - name: Upload review artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-review
          path: |
            clang-tidy-review-output.json
            clang-tidy-review-metadata.json
