name: Clang-Tidy Review

on:
  pull_request:
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - 'libs/**'
      - '.github/workflows/clang-tidy-review.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  clangtidy:
    runs-on: ubuntu-latest
    name: Clang-Tidy

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      #
      #      - name: Setup ALGLIB
      #        run: |
      #          git clone https://github.com/S-Dafarra/alglib-cmake.git
      #          cd alglib-cmake
      #          mkdir alglib_build && cd alglib_build
      #          cmake ..
      #          make -j4
      #          sudo make install

      - name: Review code with Clang-Tidy
        uses: ZedThree/clang-tidy-review@v0.18.0
        id: review
        with:
          cmake_command: >
            (git clone https://github.com/S-Dafarra/alglib-cmake.git && cd alglib-cmake && mkdir build && cd build && cmake .. && make -j4 && sudo make install && cd ../..);
            cmake . -B build
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DFICTION_CLI=ON
            -DFICTION_TEST=ON
            -DFICTION_EXPERIMENTS=ON
            -DFICTION_ALGLIB=ON
            -DCMAKE_INSTALL_PREFIX=../alglib-cmake/build
            -DMOCKTURTLE_EXAMPLES=OFF
          build_dir: build
          config_file: '.clang-tidy'
          exclude: 'libs/*, docs/*, benchmarks/*, bib/*'
          split_workflow: true

      - name: Make sure that the review file exists
        id: check-review-output
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: 'clang-tidy-review-output.json'
          ignore_case: true

      - name: Upload review artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-review
          path: |
            clang-tidy-review-output.json
            clang-tidy-review-metadata.json
