name: Clang-Tidy Review

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false # don't checkout submodules

      # Optionally generate compile_commands.json

      - name: Review code with Clang-Tidy
        uses: ZedThree/clang-tidy-review@v0.10.0
        with:
          config_file: '.clang-tidy'
          exclude: 'libs/*, docs/*, benchmarks/*, bib/*'

        id: review
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
