name: 🐳 Docker Image

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - 'libs/**'
      - '.github/workflows/docker-image.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - '!bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - 'libs/**'
      - '.github/workflows/docker-image.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - '!bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the Docker image
        run: docker build --build-arg NUMBER_OF_JOBS=4 . --file Dockerfile --tag fiction:$(date +%s)
