name: IWYU

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'libs/**'
      - '.github/workflows/iwyu.yml'

jobs:
  iwyu:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake to create compilation database
        working-directory: ${{github.workspace}}
        run: >
          cmake . -B build
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DFICTION_CLI=ON
          -DFICTION_TEST=ON
          -DFICTION_EXPERIMENTS=ON
          -DMOCKTURTLE_EXAMPLES=OFF

      - name: Run Include What You Use
        uses: EmilGedda/include-what-you-use-action@v1.0
        with:
          compilation-database-path: ${{github.workspace}}/build/
          output-format: 'iwyu' # Or 'clang'
          no-error: 'false'
