name: macOS CI

on:
  push:
    branches-ignore:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ macos-10.15 ]  # macos-11 when supported
        compiler: [ g++-9, g++-10, clang++ ]  # clang++12

    name: ${{matrix.os}} with ${{matrix.compiler}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build

        run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_PROGRESS_BARS=OFF -DFICTION_TEST=ON -DWARNINGS_AS_ERRORS=OFF

#      - name: Cache Z3
#        uses: actions/cache@v2
#        id: cache-z3
#        with:
#          path: ${{github.workspace}}/build/z3
#          key: ${{matrix.os}}_${{matrix.compiler}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash

        run: cmake --build . --config $BUILD_TYPE -j3  # macOS runners provide 3 cores

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE --verbose
