name: 🐍 • Docstring Generator

on:
  push:
    paths:
      - '**/*.hpp'
      - '.github/workflows/pyfiction-docstring-generator.yml'
  pull_request:
    paths:
      - '**/*.hpp'
      - '.github/workflows/pyfiction-docstring-generator.yml'
  workflow_dispatch:

jobs:
  get_docstrings:
    name: 🐍 Auto-generate docstrings for pyfiction from C++ code
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"
          cache: 'pip'

      - name: Install pybind11_mkdoc and clang
        working-directory: ${{ github.workspace }}
        run: pip install pybind11_mkdoc clang==15.0.7

      - name: Create docstrings file
        working-directory: ${{ github.workspace }}
        run: touch ${{ github.workspace }}/pybind11_mkdoc_docstrings.hpp

      - name: Run pybind11_mkdoc
        working-directory: ${{ github.workspace }}
        run: >
          python3
          -m pybind11_mkdoc
          -o ${{ github.workspace }}/bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
          -D FICTION_Z3_SOLVER
          `find ${{ github.workspace }}/include/fiction -name "*.hpp" -print`

      - name: Upload docstrings as an artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
          overwrite: true

      - name: Add and Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m ":memo: Update pyfiction docstrings"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}
