name: pyfiction CI

on:
  push:
    paths:
      - 'bindings/pyfiction/**'
      - '**/*.py'
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - 'libs/**'
      - '.github/workflows/python-bindings.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  Z3_VERSION: 4.10.0
  ENABLE_Z3: 'ON'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python_version: [ '3.7.x', '3.8.x', '3.9.x', '3.10.x', '3.11.x' ]
        include:
          - os: ubuntu-latest
            z3_platform: linux
          - os: macos-latest
            z3_platform: macOS
          - os: windows-latest
            z3_platform: windows
      fail-fast: false  # allow other jobs to finish even if one fails

    name: pyfiction on ${{matrix.os}} with Python ${{matrix.python_version}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: '${{matrix.os}}-pyfiction'
          variant: ccache
          save: true
          max-size: 10G

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}
          cache: 'pip'

      - if: runner.os == 'Linux'
        name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Setup Z3 Solver
        id: z3
        uses: cda-tum/setup-z3@v1
        with:
          version: ${{env.Z3_VERSION}}
          platform: ${{matrix.z3_platform}}
          architecture: x64
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build pyfiction
        working-directory: ${{github.workspace}}
        run: z3=${{env.ENABLE_Z3}} pip install '.[test]'

      - name: Test
        working-directory: ${{github.workspace}}/bindings/pyfiction/test
        run: python -m unittest discover --verbose
