name: pyfiction Collect Docstrings

on: workflow_dispatch

jobs:  
  get_docstrings:    
    name: collect docstrings    
    runs-on: ubuntu-latest  
    steps:      
      - name: Setup Python        
        uses: actions/setup-python@v4        
        with:          
          python-version: "3.11.x" 
          cache: 'pip'

      - name: Clone Repository        
        uses: actions/checkout@v3        
        with:          
          submodules: recursive            

      - name: Install pybind11_mkdoc and clang
        working-directory: ${{ github.workspace }}        
        run: pip install pybind11_mkdoc clang==14        

      - name: create docstring file
        working-directory: ${{ github.workspace }}  
        run: touch ${{ github.workspace }}/docstrings.hpp

      - name: run mkdoc        
        working-directory: ${{ github.workspace }}        
        run: python3 -m pybind11_mkdoc -o ${{ github.workspace }}/docstrings.hpp -D FICTION_Z3_SOLVER `find ${{ github.workspace }}/include/fiction -name "*.hpp" -print`

      - uses: actions/upload-artifact@v3        
        with:          
          name: upload docstrings          
          path: ${{ github.workspace }}/docstrings.hpp
